// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrg2AZHytTmKHt3tPNOCF-skWMXlgUfM',
    appId: '1:268105183404:web:a350090936ed4c396f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    authDomain: 'translationapp-621e9.firebaseapp.com',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdOg_LxgFh3wvs48b8pYrA1HM-yJbHKOw',
    appId: '1:893830471888:android:96ac85ffd14dd05f61fed5',
    messagingSenderId: '893830471888',
    projectId: 'itranslation-1981b',
    storageBucket: 'itranslation-1981b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-nKoj4yOYR5XZqz4ORR5Q3tOfvFzq1s',
    appId: '1:893830471888:ios:e2d78ddc5ea0bffe61fed5',
    messagingSenderId: '893830471888',
    projectId: 'itranslation-1981b',
    storageBucket: 'itranslation-1981b.firebasestorage.app',
    iosClientId: '893830471888-n30e0dassi2mcgje7erve2clc6079dq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.norskTolk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB98mKt8sOvfe8f3Vvp7V5mRT9evPGTmA',
    appId: '1:268105183404:ios:0ca7505c0b2fc0056f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
    iosBundleId: 'com.example.norskTolk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYrg2AZHytTmKHt3tPNOCF-skWMXlgUfM',
    appId: '1:268105183404:web:207789d0619ba9086f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    authDomain: 'translationapp-621e9.firebaseapp.com',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
  );
}