// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrg2AZHytTmKHt3tPNOCF-skWMXlgUfM',
    appId: '1:268105183404:web:a350090936ed4c396f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    authDomain: 'translationapp-621e9.firebaseapp.com',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBap_EW5y2ta_gMG4dSjds_Bl-ww1KgMDY',
    appId: '1:268105183404:android:c4a2efa1cf82e9af6f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB98mKt8sOvfe8f3Vvp7V5mRT9evPGTmA',
    appId: '1:268105183404:ios:0ca7505c0b2fc0056f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
    iosBundleId: 'com.example.norskTolk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB98mKt8sOvfe8f3Vvp7V5mRT9evPGTmA',
    appId: '1:268105183404:ios:0ca7505c0b2fc0056f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
    iosBundleId: 'com.example.norskTolk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYrg2AZHytTmKHt3tPNOCF-skWMXlgUfM',
    appId: '1:268105183404:web:207789d0619ba9086f6f09',
    messagingSenderId: '268105183404',
    projectId: 'translationapp-621e9',
    authDomain: 'translationapp-621e9.firebaseapp.com',
    storageBucket: 'translationapp-621e9.firebasestorage.app',
  );
}
